# ===================================
#  Relation Behavior Config
# ===================================

format_locales:
    label: utopigs.localize::lang.fields.format_locale
    view:
        list: $/utopigs/localize/models/currencyformat_locale/columns.yaml
        toolbarButtons: create|delete
    manage:
        form: $/utopigs/localize/models/currencyformat_locale/fields.yaml
        recordsPerPage: 10
